#cloud-config
cloud_final_modules:
  - [ users-groups,always ]
users:
  - name: default
  - name: player
    shell: /bin/bash
    ssh_authorized_keys:
      - command="/simulator/scripts/starting_point" ${player_public_key}
package_update: true
package_upgrade: true
