#!/bin/bash
#
# Run various checks before starting deployment
#

set -eo pipefail

##------------------------------------------------------------------
# start of functions

validate_aws() {

if [ "${target}" = "aws" ]; then

	echo -n "Checking aws cli available.."

	if [[ $(command -v aws) ]]; then
		echo "available"
	else
		echo "not available, check PATH"
		exit 1
	fi

	echo -n "Checking AWS Region.."

	if [[ $(aws configure get region) ]]; then
		echo "defined"
	elif [ -z "${AWS_REGION}" ]; then
		echo "not defined"
		exit 1
	else
		echo "not defined"
		exit 1
	fi
fi
}

validate_keys() {
if [ -z "${ignoreKeys}" ]; then
	echo -n "Checking for old ssh keys.."

	ls ~/.ssh/cp_simulator_* > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "None found"
	else
		echo "existing keys found, please delete"
		exit 1
	fi
fi

}

## end of functions
##------------------------------------------------------------------

## Main body

while getopts "t:ih" opt; do
	case "$opt" in
		t) target="$OPTARG"	;;
		i) ignoreKeys=1		;;
		h|*) echo "Usage:"
		   echo "$0 -t -i -h"
		   echo "-t target to build against, i.e aws"
		   echo "-i ignore ssh key checking, useful when starting container againt existing envionment"
		   echo "-h this help"
		   echo "examples:"
		   echo "$0 -t aws"
		   echo "$0 -t aws -i"
		   exit
	esac
done

[ "${target}" = "aws" ] && validate_aws

make run

