ARG GOLANG_IMAGE=golang:1.22.3-alpine3.20@sha256:7e788330fa9ae95c68784153b7fd5d5076c79af47651e992a3cdeceeb5dd1df0
ARG GOLANGCI_LINT_IMAGE=golangci/golangci-lint:latest@sha256:e699df940be1810b08ba6ec050bfc34cc1931027283b5a7f607fb6a67b503876
# last MPL2.0 release
ARG PACKER_IMAGE=hashicorp/packer:1.9.5@sha256:be65862d28fb642c0acac580a9eab9e95c3e289f07012d09c0609ec9829a85ba
# last MPL2.0 release
ARG TERRAFORM_IMAGE=hashicorp/terraform:1.5.7@sha256:9fc0d70fb0f858b0af1fadfcf8b7510b1b61e8b35e7a4bb9ff39f7f6568c321d
ARG UBUNTU_IMAGE=ubuntu:noble@sha256:3f85b7caad41a95462cf5b787d8a04604c8262cdcdf9a472b8c52ef83375fe15

FROM ${GOLANGCI_LINT_IMAGE}

WORKDIR /app

COPY . .

RUN /usr/bin/golangci-lint run -v -c .golangci.yml

FROM ${GOLANG_IMAGE} as BUILDER

WORKDIR /build

COPY go.* ./
RUN go mod download

COPY . ./

RUN go build -v -o /simulator cmd/container/main.go

FROM ${PACKER_IMAGE} as PACKER
FROM ${TERRAFORM_IMAGE} as TERRAFORM
FROM ${UBUNTU_IMAGE}

WORKDIR /simulator

COPY --from=PACKER /bin/packer /usr/local/bin/packer
COPY --from=TERRAFORM /bin/terraform /usr/local/bin/terraform

RUN apt update && \
  apt install -y ca-certificates openssh-client ansible-core && \
  rm -rf /var/lib/apt/lists/* && \
  ansible-galaxy collection install kubernetes.core

COPY --from=BUILDER /simulator /usr/local/bin/simulator

USER ubuntu

ENTRYPOINT ["/usr/local/bin/simulator"]
