apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ii-mgmt-np
  namespace: ii-prod
spec:
  podSelector:
    matchLabels:
      app: ii
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ii-mgmt-np
  namespace: ii-prod
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 8080
    - port: 5724