apiVersion: v1
kind: Service
metadata:
  name: mgmt-service
  namespace: ii-prod
spec:
  type: NodePort
  selector:
    app: ii
  ports:
  - name: mgmt
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: admin
    port: 5724
    targetPort: 5724
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ii-mgmt-np
  namespace: ii-prod
spec:
  podSelector:
    matchLabels:
      app: ii
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - port: 8080
    - port: 5724
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ii-mgmt
  namespace: ii-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: mgmt-service
            port:
              number: 80
      - path: "/backdoor"
        pathType: Prefix
        backend:
          service:
            name: mgmt-service
            port:
              number: 5724