apiVersion: v1
kind: Namespace
metadata:
  name: ci-server-vulnerability
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-access-key
  namespace: ci-server-vulnerability
type: Opaque
data:
  SECRET_ACCESS_KEY: ZmxhZ19jdGZ7YmYzODM1ZjM0M2NiNGJkZH0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: jenk-5ym3
  name: jenk-5ym3
  namespace: ci-server-vulnerability
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenk-5ym3
  template:
    metadata:
      labels:
        name: jenk-5ym3
    spec:
      containers:
      - image: controlplane/jenkins-simulator:root
        imagePullPolicy: IfNotPresent
        name: jenk-5ym3
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
          readOnly: true
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: ci-server-vulnerability
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: secret-access-key
              key: SECRET_ACCESS_KEY
