apiVersion: v1
kind: Service
metadata:
  name: secret-store
  namespace: private-services
spec:
  selector:
    app: secret-store
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: client-id
  namespace: private-services
type: Opaque
data:
  id: cG9kLWNoZWNrZXI=
---
apiVersion: v1
kind: Secret
metadata:
  name: ss-psql-pw
  namespace: private-services
type: Opaque
data:
  password: cGVyc2lzdGVudGRhdGFzdG9yZTRwZ3NxbHNlY3JldHN0b3Jl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-store
  namespace: private-services
  labels:
    app: secret-store
spec:
  selector:
    matchLabels:
      app: secret-store
  replicas: 1
  template:
    metadata:
      labels:
        app: secret-store
    spec:
      nodeName: master-1
      initContainers:
        - name: wait-for-db
          image: cgr.dev/chainguard/wait-for-it
          args:
            - --host=pgsql.backend.svc.cluster.local
            - --port=5432
            - --timeout=300
      containers:
        - name: secret-store
          image: docker.io/controlplaneoffsec/identity-theft:secret-store
          env:
            - name: DB_HOST
              value: pgsql.backend.svc.cluster.local
            - name: DB_USER
              value: secret-storer
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ss-psql-pw
                  key: password
            - name: DB_NAME
              value: secretstore
            - name: DB_PORT
              value: "5432"
            - name: SSL_MODE
              value: disable
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: client-id
                  key: id
            - name: AUTH0_DOMAIN
              value: http://dex.dex.svc.cluster.local:5556/dex
          ports:
            - containerPort: 5050
              name: http
