apiVersion: v1
kind: Namespace
metadata:
  name: 3301b-supervillians-lair

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: 3301b-supervillians-lair
  namespace: 3301b-supervillians-lair

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 3301b-supervillians-lair
  namespace: 3301b-supervillians-lair
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: 3301b-supervillians-lair
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: admin

---

kind: Service
apiVersion: v1
metadata:
  name: jumpbox
  namespace: 3301b-supervillians-lair
spec:
  selector:
    name: jumpbox
  type: NodePort
  ports:
  - port: 22
    nodePort: 30022
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: jumpbox
  name: jumpbox
  namespace: 3301b-supervillians-lair
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jumpbox
  template:
    metadata:
      labels:
        name: jumpbox
    spec:
      serviceAccountName: 3301b-supervillians-lair
      containers:
      - image: controlplane/insecure-ssh
        imagePullPolicy: IfNotPresent
        name: jumpbox
        ports:
        - containerPort: 22

---

apiVersion: v1
kind: Secret
metadata:
  name: usercreds
  namespace: 3301b-supervillians-lair
type: Opaque
data:
  USER_CREDS_PASSWORD: ZmxhZ19jdGZ7MmZhYzUzYTNiYWU3YWNhMX0K
