apiVersion: v1
kind: Namespace
metadata:
  name: node-shock-tactics
---
apiVersion: v1
kind: Secret
metadata:
  name: passwd
  namespace: node-shock-tactics
type: Opaque
data:
   password: RGFyaXVzaXNiYWQ=
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: shock-target
  name: shock-target
  namespace: node-shock-tactics
spec:
  selector:
    matchLabels:
      name: shock-target
  template:
    metadata:
      labels:
        name: shock-target
    spec:
      containers:
      - image: nginx
        
        imagePullPolicy: IfNotPresent
        name: shock-target
        ports:
        - containerPort: 80
        volumeMounts:
        - name: passwd
          mountPath: "/super/secret"
          readOnly: true
      volumes:
      - name: passwd
        secret:
          secretName: passwd
