---

- name: Install calico network
  ansible.builtin.include_role:
    name: cluster-network
    tasks_from: calico

- name: Apply K8s manifests
  kubernetes.core.k8s:
    definition: "{{ lookup('ansible.builtin.file', 'manifests/01-scenario.yaml') | from_yaml_all }}"
    state: "{{ state }}"
  become: no

- name: Set starting point
  ansible.builtin.include_role:
    name: starting-point
    tasks_from: pod
  vars:
    namespace: sea
    pod: dark-tide

- name: Copy challenge
  ansible.builtin.include_role:
    name: starting-point
    tasks_from: challenge
  vars:
    challenge_content: "{{ lookup('ansible.builtin.file', 'files/challenge.txt') }}"
