## Indian Ocean Access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terrible-disguise
  namespace: southern
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: third-mate
  namespace: indian
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: third-mate-rb
  namespace: indian
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: third-mate
subjects:
- kind: ServiceAccount
  name: terrible-disguise
  namespace: southern
---
## Southern Resources
apiVersion: v1
kind: Pod
metadata:
  name: whydah-galley
  namespace: southern
spec:
    serviceAccountName: terrible-disguise
    containers:
    - name: whydah
      image: ttl.sh/whga-t3g462442s-wakeward:12h
      # image: docker.io/controlplaneoffsec/seven-seas:whydah-galley
      command: ["sleep", "2d"]
      securityContext:
        allowPrivilegeEscalation: false
      volumeMounts:
        - mountPath: /mnt/
          name: area
    volumes:
    - hostPath:
        path: /mnt
        type: Directory
      name: area
    restartPolicy: Always
    nodeName: k8s-node-1
---
## South Atlantic Access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: second-mate
  namespace: south-pacific
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - namespace
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: second-mate-rb
  namespace: south-pacific
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: second-mate
subjects:
- kind: ServiceAccount
  name: terrible-disguise
  namespace: southern

