apiVersion: v1
kind: Pod
metadata:
  name: royal-fortune
  namespace: north-pacific
  labels:
    ship: royal-fortune
spec:
    hostPID: true
    containers:
    - name: royal-fortune
      # image: docker.io/controlplaneoffsec/seven-seas:royal-fortune
      image: ttl.sh/rf-ssh-552341sa-wakeward:12h
      ports:
      - containerPort: 2222
        name: coordinates
      securityContext:
        privileged: true
    nodeName: k8s-master-0
---
apiVersion: v1
kind: Service
metadata:
  name: plot-a-course
  namespace: north-pacific
spec:
  selector:
    ship: royal-fortune
  ports:
  - protocol: TCP
    port: 22
    targetPort: 2222