#cloud-config

# wait for an internet connection
bootcmd:
  - until ping -W 1 -c1 8.8.8.8 >/dev/null; do sleep 1; done
  - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

package_update: true
package_upgrade: false
disable_root: false

apt:
  source:
    kubernetes:
      source: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'

system_info:
  apt_get_command: [
    "apt-get",
    "--option=Dpkg::Options::=--force-confold",
    "--option=Dpkg::Options::=--force-unsafe-io",
    "--assume-yes",
    "--quiet",
    "--allow-downgrades",
    "--option=Dpkg::Lock::Timeout=-1"
  ]

packages:
  - figlet
  - awscli
  - [kubectl, 1.20.*]

hostname: "internal"

write_files:
  - path: /etc/bash.bashrc
    permissions: '0755'
    content: !!binary |
      ${host_bashrc}
  - path: /root/authorized_keys.sh
    permissions: '0755'
    content: !!binary |
      ${authorized_keys_script}
  - path: /root/.inputrc
    permissions: '0755'
    content: !!binary |
      ${host_inputrc}
  - path: /root/.bash_aliases
    permissions: '0755'
    content: !!binary |
      ${host_aliases}
  - path: /etc/default/motd-news
    owner: root:root
    permissions: '0644'
    content: |
      ENABLED=0
  - path: /etc/pam.d/sshd
    owner: root:root
    permissions: '0644'
    content: |
      # Defaults with comments removed and motd disabled
      @include common-auth
      account    required     pam_nologin.so
      @include common-account
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
      session    required     pam_loginuid.so
      session    optional     pam_keyinit.so force revoke
      @include common-session
      session    optional     pam_mail.so standard noenv # [1]
      session    required     pam_limits.so
      session    required     pam_env.so # [1]
      session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open
      @include common-password
  - path: /etc/docker/daemon.json
    owner: root:root
    permissions: "0644"
    content: |
      {"registry-mirrors":["https://mirror.gcr.io"]}

runcmd:
  - "/root/authorized_keys.sh ${github_usernames} && rm -rf /root/authorized_keys.sh"

  - 'mkdir -pv /root/.kube/'
  - 'while true; do aws s3 ls s3://${s3_bucket_name}/config > /dev/null; if [ $? -ne 0 ]; then sleep 10; else break; fi; done && aws s3 cp s3://${s3_bucket_name}/config /root/.kube/ && aws s3 rm s3://${s3_bucket_name}/config'

output:
  all: '| tee -a /var/log/cloud-init-output.log'
