#cloud-config

# wait for an internet connection
bootcmd:
  - until ping -W 1 -c1 8.8.8.8 >/dev/null; do sleep 1; done

packages:
  - figlet
  - awscli
  - [kubectl, ${version}*]

hostname: "internal"

write_files:
  - path: /etc/profile.d/motd.sh
    permissions: "0775"
    content: !!binary |
      ${internal_motd}

runcmd:
  - 'mkdir -pv /root/.kube/'
  - 'while true; do aws s3 ls s3://${s3_bucket_name}/config > /dev/null; if [ $? -ne 0 ]; then sleep 10; else break; fi; done && aws s3 cp s3://${s3_bucket_name}/config /root/.kube/ && aws s3 rm s3://${s3_bucket_name}/config'
