apiVersion: v1
kind: Namespace
metadata:
  name: secret-high-ground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: secret-high-ground
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-alpine
        imagePullPolicy: Never
