#!/bin/bash

set -Eeuo pipefail

echo -e "#!/bin/bash\n" > master.sh
echo -e "# This file is automatically generated, do not edit manually" >> master.sh

sed -e "s/PATCH=.*/PATCH=\"$(base64 -w0 < _config/apiserver.patch)\"/" <(tail -n+2 master.sh.tmpl) \
    |  sed -e "s/WEBHOOK=.*/WEBHOOK=\"$(base64 -w0 < _config/falco-webhook-kubeconfig)\"/" \
    >> master.sh

chmod +x master.sh
