#!/bin/bash

set -Eeuo pipefail

echo -e "#!/bin/bash\n" > nodes-every.sh
echo -e "# This file is automatically generated, do not edit manually" >> nodes-every.sh

sed -e "s/KILL_PODS=.*/KILL_PODS=\"$(base64 -w0 < _scripts/kill_ssh.sh)\"/" <(tail -n+2 nodes-every.sh.tmpl) \
    >> nodes-every.sh

chmod +x nodes-every.sh
