apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: player
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - patch
  - get
  - list
- apiGroups:
  - ""
  resources:
  - "pods/log"
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: player
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: player
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: player
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenet
  labels:
    app: tenet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenet
  template:
    metadata:
      labels:
        app: tenet
    spec:
      containers:
      - name: tenet
        image: docker.io/jpts/app:latest
        env:
        - name: TENET
          valueFrom:
            configMapKeyRef:
              name: time
              key: timeBackwards
        - name: SOMETHING
          value: 074c533d000d550518350a0b517255545655521176290c0d154e
        livenessProbe:
          exec:
            command:
            - iGuessYouGuysArentReadyForThat
            - /but/your/kids/are/gonna/love/it
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time
data:
  timeBackwards: "1"
