apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: player
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - "pods/log"
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: player
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: player
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: player
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenet
  labels:
    app: tenet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenet
  template:
    metadata:
      labels:
        app: tenet
    spec:
      containers:
      - name: tenet
        image: 035655476617.dkr.ecr.eu-west-1.amazonaws.com/tenet:0.1
        env:
        - name: TENET
          valueFrom:
            secretKeyRef:
              name: tenet
              key: tenet
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: tenet
data:
  tenet: MQ==
