name: Bug report
description: Create a report to help us improve
title: ""
labels: [bug]
assignees: ""
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "Tell us what happens instead of the expected behavior..."
      render: markdown
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the behavior
      description: "Please share the steps to reproduce the issue:"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "Explain what you expected to happen..."
      render: markdown
    validations:
      required: true
  - type: markdown
    attributes:
      value: "You can add screenshots or additional context below."
  - type: file
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "Any other information or context..."
      render: markdown
    validations:
      required: false
