---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: the-quiet-place
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: developer
  namespace: the-quiet-place
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: project-developer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: developer-bind
  namespace: the-quiet-place
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-developer
subjects:
- kind: ServiceAccount
  name: developer
  namespace: the-quiet-place
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: start
  namespace: the-quiet-place
spec:
  serviceAccountName: developer
  containers:
  - image: docker.io/library/debian:11-slim
    command: ["sleep", "2d"]
    name: start
  restartPolicy: Always
---
