apiVersion: v1
kind: Pod
metadata:
  name: tools
  namespace: private-services
  labels:
    app: terminal
spec:
  containers:
  - image: docker.io/controlplane/sectools:latest
    command: ["sleep", "2d"]
    name: tools
  restartPolicy: Always