#
apiVersion: v1
kind: Namespace
metadata:
  name: public
  labels:
    ns: public
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    ns: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: public-services
  labels:
    ns: public-services
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    ns: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: private-services
  labels:
    ns: private-services
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
  labels:
    ns: dex
---
