#!/usr/bin/env bashBASEURL="http://localhost:30080"

set -Eeuo pipefail
shopt -s expand_aliases

# Configure Gitea
curl -sSL https://dl.gitea.com/tea/0.9.2/tea-0.9.2-linux-amd64 -o tea
install -s tea /usr/local/bin

GITEA_SERVER_USER="ctf_admin"
GITEA_SERVER_PASSWORD="ahXeehohsoo2suej4tee0ol5xeeteM1w"
BASEURL="http://localhost:30080"

# shellcheck disable=SC2139
alias curlj="curl -u \"$GITEA_SERVER_USER:$GITEA_SERVER_PASSWORD\" -H 'Content-type: application/json'"

#CSRF=$(curl -sS -c cookie.jar "$BASEURL" --retry 3 --retry-connrefused --retry-delay 5 | awk -F' ' '/csrfToken/ {print $2}' | tr -d "',")
#curl -sSL -b cookie.jar -c cookie.jar -XPOST "$BASEURL/user/login" -d "user_name=$GITEA_SERVER_USER&password=$GITEA_SERVER_PASSWORD&_csrf=$CSRF"
#CSRF=$(awk '/_csrf/ {print $7}' cookie.jar)
#RESP=$(curl -sSL -b cookie.jar -c cookie.jar -XPOST "$BASEURL/user/settings/applications" -d "_csrf=$CSRF&name=cli&scope=repo&scope=admin%3Aorg&scope=admin%3Apublic_key&scope=admin%3Arepo_hook&scope=admin%3Aorg_hook&scope=notification&scope=user&scope=delete_repo&scope=package&scope=admin%3Aapplication&scope=sudo" -v 2>&1)
#TOKEN=$(echo "$RESP" | grep -F "macaron_flash" | perl -0777 -pe 's/.*info%3D(.*)%26success%3DYour%2Bnew%2Btoken.*/\1/msg')

function get_cli_token() {
    set -x
    TUSER=${1:-"$GITEA_SERVER_USER"}
    TPASS=${2:-"$GITEA_SERVER_PASSWORD"}
    SUFFIX=$(tr -dc a-z0-9 </dev/urandom | head -c 6)
    JSON=$(curl -u "$TUSER:$TPASS" -H 'Content-type: application/json' -sS --fail-with-body "$BASEURL/api/v1/users/$TUSER/tokens" -XPOST --retry 3 --retry-connrefused --retry-delay 5 -d "{\"name\":\"cli_token_$SUFFIX\",\"scopes\":[\"all\"]}")
    echo "$JSON" | jq .sha1 -r
    set +x
}
TOKEN=$(get_cli_token "ctf_admin")

if [[ "$TOKEN" == "null" ]]; then
    echo "Failed to get cli TOKEN"
    exit 1
fi
rm -f /root/.config/tea/config.yml
tea login add -n ctf -u http://localhost:30080 -t "$TOKEN"
tea login default ctf

DEV1="{\"full_name\": \"Jonathan Castillo\", \"login_name\": \"jcastillo\", \"username\": \"jcastillo\", \"email\": \"jcastillo@rescue.drop\", \"password\": \"9zvB2cQf2tdC\"}"
DEV2="{\"full_name\": \"Lauren Mcfarland\", \"login_name\": \"lmcfarland\", \"username\": \"lmcfarland\", \"email\": \"lmcfarland@rescue.drop\", \"password\": \"kmyPlZv8w3Cj\"}"
DEV3="{\"full_name\": \"Jacob Gutierrez\", \"login_name\": \"jgutierrez\", \"username\": \"jgutierrez\", \"email\": \"jgutierrez@rescue.drop\", \"password\": \"EpLLztbxH7pu\"}"
DEV4="{\"full_name\": \"Bryan Thompson\", \"login_name\": \"bthompson\", \"username\": \"bthompson\", \"email\": \"bthompson@rescue.drop\", \"password\": \"NZ7HlHtgG6a6\"}"
DEV5="{\"full_name\": \"Randy Nguyen\", \"login_name\": \"rnguyen\", \"username\": \"rnguyen\", \"email\": \"rnguyen@rescue.drop\", \"password\": \"2moaH42uXi1H\"}"
DEV6="{\"full_name\": \"Alexander Scott\", \"login_name\": \"ascott\", \"username\": \"ascott\", \"email\": \"ascott@rescue.drop\", \"password\": \"gbiJIiAg4zKj\"}"
DEV7="{\"full_name\": \"Jennifer Lucas\", \"login_name\": \"jlucas\", \"username\": \"jlucas\", \"email\": \"jlucas@rescue.drop\", \"password\": \"9YCuacxJGB5s\"}"
DEV8="{\"full_name\": \"Kristy Garner\", \"login_name\": \"kgarner\", \"username\": \"kgarner\", \"email\": \"kgarner@rescue.drop\", \"password\": \"lqeQkqiU3GnW\"}"
DEV9="{\"full_name\": \"Joyce Vazquez\", \"login_name\": \"jvazquez\", \"username\": \"jvazquez\", \"email\": \"jvazquez@rescue.drop\", \"password\": \"f87wMWnJIyOu\"}"
OPS1="{\"full_name\": \"Benjamin Gibbs\", \"login_name\": \"bgibbs\", \"username\": \"bgibbs\", \"email\": \"bgibbs@rescue.drop\", \"password\": \"p9i41rFv4QUf\"}"
OPS2="{\"full_name\": \"Jason Cox\", \"login_name\": \"jcox\", \"username\": \"jcox\", \"email\": \"jcox@rescue.drop\", \"password\": \"B6cBTNcweE45\"}"
OPS3="{\"full_name\": \"Katherine Perez\", \"login_name\": \"kperez\", \"username\": \"kperez\", \"email\": \"kperez@rescue.drop\", \"password\": \"aSLBQtc7eH64\"}"
REV1="{\"full_name\": \"Dawn Shaw\", \"login_name\": \"dshaw\", \"username\": \"dshaw\", \"email\": \"dshaw@rescue.drop\", \"password\": \"ZPkyZABfsTD9\"}"
REV2="{\"full_name\": \"Ian Ramos\", \"login_name\": \"iramos\", \"username\": \"iramos\", \"email\": \"iramos@rescue.drop\", \"password\": \"B6ejWLgmcmE1\"}"
REV3="{\"full_name\": \"Julia Flynn\", \"login_name\": \"jflynn\", \"username\": \"jflynn\", \"email\": \"jflynn@rescue.drop\", \"password\": \"mawNbk5JFi0W\"}"

ALL=("$DEV1" "$DEV2" "$DEV3" "$DEV4" "$DEV5" "$DEV6" "$DEV7" "$DEV8" "$DEV9" "$OPS1" "$OPS2" "$OPS3" "$REV1" "$REV2" "$REV3")
DEV=("$DEV1" "$DEV2" "$DEV3" "$DEV4" "$DEV5" "$DEV6" "$DEV7" "$DEV8" "$DEV9")
OPS=("$OPS1" "$OPS2" "$OPS3")
REV=("$REV1" "$REV2" "$REV3")

# Create all users
for USER in "${ALL[@]}"
do
    USERNAME=$(echo "$USER" | jq .username -r)
    DATA=$(echo "$USER" | jq '.must_change_password = false' )
    JSON=$(curlj "$BASEURL/api/v1/admin/users" -XPOST -d "$DATA")
    SUCCESS=$(echo "$JSON" | jq .active -r)
    if [[ "$SUCCESS" != "true" ]]; then
        echo "Creating $USERNAME failed"
        exit 1
    fi
done

# Create token for compromised user
TOKEN2=$(get_cli_token "iramos" "B6ejWLgmcmE1")
echo "$TOKEN2" > /tmp/iramos-token

# Set Admin user to private
DATA="{\"login_name\":\"$GITEA_SERVER_USER\",\"visibility\":\"private\"}"
JSON=$(curlj "$BASEURL/api/v1/admin/users/$GITEA_SERVER_USER" -XPATCH -d "$DATA")
SUCCESS=$(echo "$JSON" | jq .visibility -r)
if [[ "$SUCCESS" != "private" ]]; then
    echo "Editing user $USER failed"
    exit 1
fi

# Create org structure
ORG="rescue-drop"
tea org create "$ORG"
for NAME in developers devops reviewers; do
    DATA="{\"name\":\"$NAME\",\"permission\":\"write\",\"can_create_org_repo\":false,\"units\":[\"repo.code\",\"repo.pulls\"],\"includes_all_repositories\": true}"
    JSON=$(curlj "$BASEURL/api/v1/orgs/$ORG/teams" -XPOST -d "$DATA")
    SUCCESS=$(echo "$JSON" | jq .id -r)
    if [[ "$SUCCESS" == "null" ]]; then
        echo "Creating team $NAME failed"
        exit 1
    fi
done

# Get Team ID to prevent sequence inconsistencies
DEV_TEAM=$(curlj "$BASEURL/api/v1/orgs/$ORG/teams" | jq '.[] | select(.name=="developers") | .id')
for USER in "${DEV[@]}"
do
    USERNAME=$(echo "$USER" | jq .username -r)
    JSON=$(curlj "$BASEURL/api/v1/teams/$DEV_TEAM/members/$USERNAME" -X PUT)
    SUCCESS=$(echo "$JSON" | jq .errors -r)
    if [[ "$SUCCESS" == "null" ]]; then
        echo "Putting $USERNAME into developers failed"
        exit 1
    fi
done

OPS_TEAM=$(curlj "$BASEURL/api/v1/orgs/$ORG/teams" | jq '.[] | select(.name=="devops") | .id')
for USER in "${OPS[@]}"
do
    USERNAME=$(echo "$USER" | jq .username -r)
    JSON=$(curlj "$BASEURL/api/v1/teams/$OPS_TEAM/members/$USERNAME" -X PUT)
    SUCCESS=$(echo "$JSON" | jq .errors -r)
    if [[ "$SUCCESS" == "null" ]]; then
        echo "Putting $USERNAME into devops failed"
        exit 1
    fi
done

REV_TEAM=$(curlj "$BASEURL/api/v1/orgs/$ORG/teams" | jq '.[] | select(.name=="reviewers") | .id')
for USER in "${REV[@]}"
do
    USERNAME=$(echo "$USER" | jq .username -r)
    JSON=$(curlj "$BASEURL/api/v1/teams/$REV_TEAM/members/$USERNAME" -X PUT)
    SUCCESS=$(echo "$JSON" | jq .errors -r)
    if [[ "$SUCCESS" == "null" ]]; then
        echo "Putting $USERNAME into reviewers failed"
        exit 1
    fi
done

# Create repo
REPO="production-image-build"
DESC="Build for our production job processing"
tea repo create --owner "$ORG" --name "$REPO" --desc "$DESC"

# Set repo features
# Requires patch
DATA='{"has_actions":true,"has_wiki":false,"has_releases":false,"has_projects":false}'
JSON=$(curlj "$BASEURL/api/v1/repos/$ORG/$REPO" -XPATCH -d "$DATA")
SUCCESS=$(echo "$JSON" | jq .has_actions -r)
if [[ "$SUCCESS" != "true" ]]; then
    echo "Editing repo $REPO failed"
    exit 1
fi

# create branch protection
set +e
read -r -d '' DATA <<EOF
{
  "rule_name": "main",
  "required_approvals": 1,
  "enable_approvals_whitelist": true,
  "approvals_whitelist_teams": ["reviewers"],
  "enable_push": true,
  "enable_push_whitelist": true,
  "push_whitelist_usernames": ["jcastillo"]
}
EOF
set -e
JSON=$(curlj "$BASEURL/api/v1/repos/$ORG/$REPO/branch_protections" -XPOST -d "$DATA")
SUCCESS=$(echo "$JSON" | jq .created_at -r)
if [[ "$SUCCESS" == "null" ]]; then
    echo "Adding branch protection for $ORG/$REPO failed"
    exit 1
fi

# Add a CI secrets
# There is no API endpoint :(

function add_secret() {
    local SECRET_NAME="$1"
    local SECRET_VALUE="$2"
    # 1st CSRF & Login
    CSRF=$(curl -sS -c cookie.jar "$BASEURL" | awk -F' ' '/csrfToken/ {print $2}' | tr -d "',")
    curl -sSL -b cookie.jar -c cookie.jar -XPOST "$BASEURL/user/login" -d "user_name=$GITEA_SERVER_USER&password=$GITEA_SERVER_PASSWORD&_csrf=$CSRF"

    # Re-fetch CSRF for safety & second req
    CSRF=$(curl -sS -c cookie.jar -b cookie.jar "$BASEURL/$ORG/$REPO/settings/secrets" | awk -F' ' '/csrfToken/ {print $2}' | tr -d "',")
    RESP=$(curl -sSL -b cookie.jar -c cookie.jar -XPOST "$BASEURL/$ORG/$REPO/settings/secrets" -d "_csrf=$CSRF&title=${SECRET_NAME}&content=${SECRET_VALUE}" -v 2>&1)
    SUCCESS=$(echo "$RESP" | grep -F "macaron_flash" | perl -0777 -pe 's/.*flash=success%3DThe%2Bsecret(.*)has%2Bbeen%2Badded.*/\1/msg')
    if [[ "$SUCCESS" == "" ]]; then
        echo "Adding CI secret ${SECRET_NAME} failed"
        exit 1
    fi
}

add_secret "DEPLOY_KEY" "storeimage"
RUNNER_KUBECONFIG=$(cat /etc/kubernetes/runner.conf)
add_secret "KUBECONFIG" "$RUNNER_KUBECONFIG"

## Order Processor Database
mkdir -p /data/db

cat <<-"EOF" | base64 -d > /data/db/orders.db
U1FMaXRlIGZvcm1hdCAzABAAAQEAQCAgAAAAEwAAAAMAAAAAAAAAAAAAAAEAAAAEAAAAAAAAAAAA
AAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATAC4/2Q0P+AACDe4ADe4PywAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDWgEHFxkZAYcPdGFibGVvcmRlcnNvcmRl
cnMCQ1JFQVRFIFRBQkxFIG9yZGVycyAoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
aWQgSU5UIFBSSU1BUlkgS0VZLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGZ1bGxu
YW1lIFRFWFQgTk9UIE5VTEwsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYWRkcmVz
cyBCTE9CIE5PVCBOVUxMLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGVtYWlsIFRF
WFQgTk9UIE5VTEwsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0ZSBURVhUIE5P
VCBOVUxMLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNyZWRpdF9jYXJkIElOVCBO
T1QgTlVMTCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjY19leHBpcmUgVEVYVCBO
T1QgTlVMTCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBvcmRlcnMgVEVYVCkrAgYX
PxkBAGluZGV4c3FsaXRlX2F1dG9pbmRleF9vcmRlcnNfMW9yZGVycwMAAAAIAAAAAA0AAAASB00A
D38PBA6EDhENjg0jDMEMUQvNC04K1QpVCdcJLwizCDcHvwdNAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHASCQEnXy0hBhcfEUJyZW5kYW4g
UHJpY2U3NTQ2NiBCZW5uZXR0IERyaXZlClJvc2FsZXNzdGFkLCBTRCAzODQyOGJwcmljZUBnbWFp
bC5jb20yMDIyLTA3LTE1AA9cZxbBW38xMi8yM2dpZnQgY2FyZHYRCQEjay8hBhchEExlYWggU2Fu
dG9zMjkxNTYgS2F5bGEgU3B1cnMgQXB0LiA5OTYKTWF0dGhld3RvbiwgSUQgMzM0Mjlsc2FudG9z
QHlhaG9vLmNvbTIwMjItMTEtMDEAAMHeKiHupjEwLzIzc2hvd2VyIGdlbHoQCQErXTUhBhcpD0dy
ZWdvcnkgU2FuY2hlejg3MTIgTmljb2xlIExvY2tzCkxha2UgR3JlZ29yeSwgTkogOTI0NDdnc2Fu
Y2hlekBob3RtYWlsLmNvbTIwMjItMTItMDQADKxv8Bm+QDEwLzMwbGFwdG9wIGNoYXJnZXJ6DwkB
I3UvIQYXHw5FcmljIEliYXJyYTk3NyBDb3VydG5leSBWaWV3IEFwdC4gMjE2CkVhc3QgTmljb2xl
dG93biwgQ1QgMTQ0ODRlaWJhcnJhQHlhaG9vLmNvbTIwMjItMDUtMTQADJ0mpZp3/DA1LzIzdXNi
IGNhYmxlgSUOCQErczMhBhdrDUp1c3RpbiBQaGlsbGlwczkxNyBKZW5uaWZlciBFeHByZXNzd2F5
IEFwdC4gODk5Ck15ZXJzdG9uLCBPUiAzNzU0OGpwaGlsbGlwc0B5YWhvby5jb20yMDIyLTEyLTE3
AAfnmAC/Ce8wNS8yNGZsYWdfY3Rme1NFQ19JTkNJREVOVF9DVVNUT01FUl9EQVRBX0RJU0NPVkVS
RUR9fA0JASlzLyEFFyMMTWVsaXNzYSBNaWxsZXI0MDIyIENyb3NzIExha2VzIFN1aXRlIDY5OQpM
YWtlIEhheWxleXRvbiwgT0ggODM4NjFtbWlsbGVyQGdtYWlsLmNvbTIwMjItMDgtMTEAhhWh+v0w
MS8yOHRvb3RoIGJydXNofgwJASF5MSEFFycLVG9kZCBMb2dhbjc1NTUgRWxpemFiZXRoIFByYWly
aWUgU3VpdGUgNTIzClJhbWlyZXpsYW5kLCBHVSA5OTA3NnRsb2dhbkBob3RtYWlsLmNvbTIwMjIt
MTItMjgEZPoUESQwNy8yNWJpcnRoZGF5IGNhcmR3CwkBK2UxIQYXHwpDaGVsc2VhIEZsb3dlcnMw
MzMgUmV5bm9sZHMgUGxhaW4KTmV3IFJlYmVjY2FiZXJnLCBXViA0NDAxNWNmbG93ZXJzQHlhaG9v
LmNvbTIwMjItMDQtMTcAATv2mCfvgjAzLzI4Z2lmdCBjYXJkfQoKASGBAS0hBhcbCUNvcnkgTGVh
Y2g2MTQyIFJpY2hhcmQgQ3Jlc2NlbnQgU3VpdGUgNjc1ClNvdXRoIFJvYmVydHBvcnQsIE5EIDYx
MDA1Y2xlYWNoQGdtYWlsLmNvbTIwMjItMDYtMjcAEHbuC45uCzA4LzMxdXNiIGtleYEBCQkBLWs1
IQYXJwhKZXJlbWlhaCBTYW5kZXJzMTA5MzEgUm9uYWxkIENlbnRlcnMKU291dGggRHVzdGluYmVy
ZywgTUkgNjEzMzNqc2FuZGVyc0Bob3RtYWlsLmNvbTIwMjItMDYtMDgAB+t/OIoo3zAxLzI1cHJp
bnRlciB0b25lcm4ICQElYTEhBhcXB0FuZ2VsYSBFdmFuczY3NDk5IFBoaWxsaXBzIExvZGdlClRp
bW90aHlidXJ5LCBMQSA1MjY1N2FldmFuc0Bob3RtYWlsLmNvbTIwMjItMDQtMTUADLiKOzPvCDAz
LzIzYnJlYWRgBwkBJUsxIQUXFQZCYWlsZXkgQWxsZW5Vbml0IDQ3MTggQm94IDcyMTQKRFBPIEFB
IDE4MDM1YmFsbGVuQGhvdG1haWwuY29tMjAyMi0wOC0wMgCSycsOyzAyLzI3bWlsa2kGCQEtSzch
BhcVBVBhdHJpY2sgV2lsbGlhbXNVbml0IDQzMTYgQm94IDE1MTUKRFBPIEFFIDM1Njk3cHdpbGxp
YW1zQGhvdG1haWwuY29tMjAyMi0wOC0wNwABN/sIgxyjMTIvMjVlZ2dzgQAFCQEjcTUhBhcpBExl
ZSBTd2VlbmV5MjY0NyBTdGFjZXkgSGlsbCBTdWl0ZSAyNDgKV2VzdCBNYXJ5dmlldywgSU4gNjg4
Mzdsc3dlZW5leUBob3RtYWlsLmNvbTIwMjItMDctMDcAF297Q4K9rTA4LzI5bGFwdG9wIGNoYXJn
ZXJxBAkBI3MtIQUXFQNKdWxpZSBEb3lsZTUwNjEgUm9tZXJvIFN0cmVhbSBTdWl0ZSAwNDgKUGF0
cmljaWF0b3duLCBPSyAwNjI0NWpkb3lsZUB5YWhvby5jb20yMDIyLTA0LTE4G9LGginkMTEvMzBz
YWx0fgMJASl1NSEFFx8CU3RldmVuIEphY2tzb241OTQxIExhd3NvbiBNYW5vcnMgU3VpdGUgOTMx
ClBvcnQgQWRhbXRvd24sIElOIDkzODIyc2phY2tzb25AaG90bWFpbC5jb20yMDIyLTAzLTMxG5rg
T0LhMTIvMjl1c2IgY2FibGV5AgkJJVsxIQYXNUV2ZWx5biBQZXJyeTk5NiBLZWxseSBNb3VudGFp
bnMKT3J0aXpmb3J0LCBGTSAwNTg5MmVwZXJyeUBob3RtYWlsLmNvbTIwMjItMTItMzAAATWm8/Gx
djEwLzMybW9iaWxlIHBob25lIGNoYXJnZXJ/AQkIJ3czIQYXIU1hcnkgUGV0ZXJzb244MTI0IE1h
eHdlbGwgVW5pb25zIEFwdC4gNjAzCk5ldyBBYmlnYWlsdG9uLCBLUyAwMDgwN21wZXRlcnNvbkB5
YWhvby5jb20yMDIyLTA4LTE0ABVbMqgogVAxMS8yOWZyeWluZyBwYW4KAAAAEg+XAA/8D/cP8Q/r
D+UP3w/ZD9MPzQ/HD8EPuw+1D68PqQ+jD50PlwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQMBARESBQMBARARBQMB
AQ8QBQMBAQ4PBQMBAQ0OBQMBAQwNBQMBAQsMBQMBAQoLBQMBAQkKBQMBAQgJBQMBAQcIBQMBAQYH
BQMBAQUGBQMBAQQFBQMBAQMEBQMBAQIDBAMJAQIDAwgJ
EOF
