category: KubeCon
difficulty: KubeCon
name: cicd
kind: cp.simulator/scenario:1.0.0
objective: Get postgres password.
tasks:
  "1":
    hints:
    sortOrder: 1
    startingPoint:
      mode: pod
      podName: jumpbox
      podNamespace: dmz
    summary: x
