on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: build-image
    runs-on: ubuntu-latest
    env:
      TOKEN: __TOKEN__
    steps:
      - name: Git Checkout
        uses: https://gitea.com/actions/checkout@v3
        with:
          token: ${{ env.TOKEN }}

      - name: test build image
        uses: docker/build-push-action@v4
        with:
          push: false
