---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: the-prestige
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: developer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: developer-list
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: developer
  namespace: the-prestige
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: developer-bind
  namespace: the-prestige
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer
subjects:
- kind: ServiceAccount
  name: developer
  namespace: the-prestige
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: developer-bind
  namespace: development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer
subjects:
- kind: ServiceAccount
  name: developer
  namespace: the-prestige
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: developer-cluster-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer-list
subjects:
- kind: ServiceAccount
  name: developer
  namespace: the-prestige
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: controlplane-allow
  namespace: the-prestige
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  - to:
    - ipBlock:
        cidr: 172.31.2.0/24
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-to-ns
  namespace: the-prestige
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: start
  namespace: the-prestige
spec:
  serviceAccountName: developer
  containers:
  - image: docker.io/library/debian:11-slim
    command: ["sleep", "2d"]
    name: start
  restartPolicy: Always
---
