---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-images
spec:
  background: false
  rules:
  - match:
      resources:
        kinds:
        - Pod
        namespaces:
        - default
        - the-prestige
        - development
    name: restrict-images
    validate:
      pattern:
        spec:
          containers:
          - image: ?*/?*:production
      message: 'Container image must match org docker.io/supersecureorg/*:production
        NOTE: I was having some trouble when I was testing this up with my perosnal
        DockerHub account, but it works now!'
  validationFailureAction: enforce
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-privilege
spec:
  background: false
  rules:
  - match:
      resources:
        kinds:
        - Pod
        namespaces:
        - default
        - the-prestige
        - development
    name: restrict-privilege
    validate:
      pattern:
        spec:
          =(initContainers):
          - =(securityContext):
              =(privileged): "false"
              =(allowPrivilegeEscalation): "false"
              =(procMount): "Default"
              =(sysctls): "null"
              =(capabilites):
                X(add): "null"
          containers:
          - =(securityContext):
              =(privileged): "false"
              =(procMount): "Default"
              =(sysctls): "null"
              =(allowPrivilegeEscalation): "false"
              =(capabilites):
                X(add): "null"
          =(hostPID): "false"
          =(hostIPC): "false"
          =(hostNetwork): "false"
          =(volumes):
            - X(hostPath): "null"
      message: 'Containers cannot be privileged. Nice try ;) HINT: is there anywhere else you could deploy an image?'
  validationFailureAction: enforce
---

