apiVersion: v1
kind: Namespace
metadata:
  name: escalate-uncover-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: process-audit
  namespace: escalate-uncover-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: db-pass
  namespace: escalate-uncover-secret
type: Opaque
data:
  password: cXdlcnR5dWlvcEt1YmVDb24hCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: keys
  namespace: escalate-uncover-secret
type: Opaque
data:
  keys.txt: QVdTX0FDQ0VTU19LRVlfSUQ9S0VZS3ViZUNvbjIwMjAKQVdTX1NFQ1JFVF9BQ0NFU1NfS0VZPVNFQ1JFVEtFWUt1YmVDb24yMDIwIQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-audit
  namespace: escalate-uncover-secret
spec:
  selector:
    matchLabels:
      app: process-audit
  template:
    metadata:
      labels:
        app: process-audit
    spec:
      serviceAccountName: process-audit
      hostPID: true
      containers:
      - name: audit
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        securityContext:
          capabilities:
            add: ["ALL"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: db
  namespace: escalate-uncover-secret
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: database
        volumeMounts:
        - name: keys
          mountPath: "/secrets"
          readOnly: true
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pass
              key: password
      volumes:
      - name: keys
        secret:
          secretName: keys
