---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ingress-edit
rules:
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-view
rules:
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-developer-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-view
subjects:
- kind: ServiceAccount
  name: ingress-developer
  namespace: engine-x-line-one
- kind: ServiceAccount
  name: ingress-nginx-one
  namespace: engine-x-line-one
- kind: ServiceAccount
  name: ingress-developer
  namespace: engine-x-line-two
- kind: ServiceAccount
  name: ingress-nginx-two
  namespace: engine-x-line-two
- kind: ServiceAccount
  name: ingress-developer
  namespace: engine-x-line-three
- kind: ServiceAccount
  name: ingress-nginx-three
  namespace: engine-x-line-three
---
