---
apiVersion: v1
data:
  flag: ZmxhZ19jdGZ7VmVoaWN1bGFyTG9jb21vdGl2ZUZpeGVyVXBwZXJ9Cg==
kind: Secret
metadata:
  name: flag
  namespace: engine-x-line-one
---
apiVersion: v1
data:
  flag: ZmxhZ19jdGZ7U2VjcmV0aXZlUGV0cm9sSGVhZH0K
kind: Secret
metadata:
  name: flag
  namespace: engine-x-line-two
---
apiVersion: v1
data:
  flag: ZmxhZ19jdGZ7Q2xvdWROYXRpdmVNZWNoYW5pY30K
kind: Secret
metadata:
  name: flag
  namespace: engine-x-line-three
---
