#!/bin/bash

! aws --version > /dev/null && { echo "Error: awscli missing or not in path"; exit 1; }

while getopts "b:p" opt; do
  case "$opt" in
    b ) bucket="$OPTARG"	;;
    p ) profile="$OPTARG"	;;
    * ) echo "Usage: $0 [-b bucketname to create] [-p profile name]"
        exit 0
  esac
done

if [[ -z ${profile} ]]; then
  cmdline="aws s3 mb s3://${bucket}"
else
  cmdline="aws s3 mb s3://${bucket} --profile ${profile}"
fi

echo -n "Creating Bucket....."
if ! $cmdline ;  then
   echo "Failed"
   status=1
else
   echo "Completed"
   status=0
fi

exit ${status}


