#!/bin/bash
#
# Simple terraform variable documentee
#

sourceDir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export belowDir=$(echo ${sourceDir}| sed -e 's/\/scripts*$//g')

if [[ ${OSTYPE} =~ ^darwin* ]]; then
	tfdoc = "terraform-docs-darwin"
elif [[ ${OSTYPE} =~ ^linux-gnu* ]]; then
	tfdoc = "terraform-docs"
else
	echo "Cannot identify OS...exiting"
	exit 1
fi

[ ! -x ${belowDir}/bin/${tfdoc} 2>/dev/null ] && { echo -e "This script requires terraform-docs available from <https://github.com/segmentio/terraform-docs>....exiting"; exit 1; }

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <base-directory>"
	exit 1
fi

directory=$1
readmeName="README-auto.md"

find "${directory}" -type d -not -path "${directory}/.git/*" -exec bash -c '${belowDir}/bin/${tfdoc} md "{}"  >  "{}"/README-auto.md;' \;

find "${directory}" -name "${readmeName}" -size 1c -type f -delete

printf "\n\033[35;1mUpdating the following READMEs with terraform-docs\033[0m\n\n"

find "${directory}" -name "${readmeName}"

