#!/bin/bash

echo -n "Checking aws cli available.."

if [[ $(command -v aws) ]]; then
	echo "available"
else
	echo "not available, check PATH"
	exit 1
fi

echo -n "Checking AWS Region defined.."

if [[ $(aws configure get region) ]]; then
	echo "defined"
elif [ -z "${AWS_REGION}" ]; then
	echo "not defined"
	exit 1
else
	echo "not defined"
	exit 1
fi

echo -n "Checking Terraform installed.."

if [[ $(command -v terraform) ]]; then
	echo "available"
else
	echo "not available, check PATH"
	exit 1
fi


