#!/bin/bash

echo -n "Checking AWS cli installed.."

if [[ $(command -v aws) ]]; then
	echo "installed"
else
	echo "not available, check PATH"
	exit 1
fi

echo -n "Checking AWS region defined.."

if [[ $(aws configure get region) ]]; then
	echo "defined"
elif [ -z "${AWS_REGION}" ]; then
	echo "not defined"
	exit 1
else
	echo "not defined"
	exit 1
fi

echo -n "Checking Terraform installed.."

if [[ $(command -v terraform) ]]; then
	echo "installed"
else
	echo "not available, check PATH"
	exit 1
fi

echo -n "Checking Docker is running.."

if [[ $(docker version) ]]; then
	echo "running"
else
	echo "not running"
	exit 1
fi

