## JumpBox Resources
apiVersion: v1
kind: Namespace
metadata:
  name: dmz
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre
  namespace: dmz
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sre-role
  namespace: dmz
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/attach
  verbs:
  - create
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/ephemeralcontainers
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dmz-sre-rb
  namespace: dmz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sre-role
subjects:
- kind: ServiceAccount
  name: sre
  namespace: dmz
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-ns-read
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-ns-read-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-ns-read
subjects:
- kind: ServiceAccount
  name: sre
  namespace: dmz
---
apiVersion: v1
kind: Pod
metadata:
  name: jumpbox
  namespace: dmz
spec:
  nodeName: k8s-node-0
  containers:
  - image: docker.io/controlplaneoffsec/kubectl:latest
    command:
      - sleep
      - inf
    name: jumpbox
    securityContext:
      allowPrivilegeEscalation: false
  restartPolicy: Always
