apiVersion: v1
kind: ServiceAccount
metadata:
  name: swashbyter
  namespace: arctic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocean-viewer-cr
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ocean-viewer-cr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocean-viewer-cr
subjects:
- kind: ServiceAccount
  name: swashbyter
  namespace: arctic
---
apiVersion: v1
kind: Pod
metadata:
  name: fancy
  namespace: arctic
  labels:
    ship: fancy
spec:
    serviceAccountName: swashbyter
    containers:
    - name: lookout
      image: docker.io/controlplaneoffsec/seven-seas:fancy
      command: ["sleep", "2d"]
      securityContext:
        allowPrivilegeEscalation: false
    restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: path-of-the-pirate
  namespace: arctic
  labels:
    ship: potp
spec:
    containers:
    - name: path-of-the-pirate
      image: docker.io/controlplaneoffsec/seven-seas:potp
      ports:
      - containerPort: 8080
        name: path
      securityContext:
        allowPrivilegeEscalation: false
    restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: the-way
  namespace: arctic
spec:
  type: NodePort
  selector:
    ship: potp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080