apiVersion: v1
kind: Namespace
metadata:
  name: phase-4-lockout
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-access-key
  namespace: phase-4-lockout
type: Opaque
data:
  SECRET_ACCESS_KEY: ZmxhZ19jdGZ7MmEzOTczNzc5MzAwNjcyOX0K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: build-tools
  name: build-tools
  namespace: phase-4-lockout
spec:
  replicas: 1
  selector:
    matchLabels:
      name: build-tools
  template:
    metadata:
      labels:
        name: build-tools
    spec:
      containers:
      - image: controlplane/jenkins-simulator:root
        imagePullPolicy: IfNotPresent
        name: build-tools
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
          readOnly: true
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: phase-4-lockout
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: secret-access-key
              key: SECRET_ACCESS_KEY
