---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    when: ansible_os_family == "Debian"

- name: Upgrade all packages to the latest version
  yum:
    name: "*"
    state: latest
    when: ansible_os_family == "RedHat"

