#cloud-config

package_update: true
package_upgrade: false
disable_root: false

# defaults with extended timeout
# timeout will become active when cloud-init updates to
# relying on apt built-in timeout functionality
system_info:
  apt_get_command: [
    "apt-get",
    "--option=Dpkg::Options::=--force-confold",
    "--option=Dpkg::Options::=--force-unsafe-io",
    "--assume-yes",
    "--quiet",
    "--option=Dpkg::Lock::Timeout=-1"
  ]

apt:
  preserve_sources_list: false
  sources:
    kubernetes:
      keyid: B53DC80D13EDEF05
      keyserver: keyserver.ubuntu.com
      source: 'deb [signed-by=$KEY_FILE] https://apt.kubernetes.io/ kubernetes-xenial main'
      append: false

users:
- default
- name: root
  shell: /bin/bash
  ssh_import_id:
%{ for user in github_usernames ~}
    - gh:${user}
%{ endfor ~}

write_files:
  - path: /etc/bash.bashrc
    permissions: "0755"
    content: !!binary |
      ${generic_bashrc}
  - path: /home/ubuntu/.inputrc
    permissions: "0755"
    content: !!binary |
      ${generic_inputrc}
  - path: /home/ubuntu/.bash_aliases
    permissions: "0755"
    content: !!binary |
      ${generic_aliases}
  - path: /etc/default/motd-news
    owner: root:root
    permissions: "0644"
    content: |
      # Don't call home to canonical
      ENABLED=0
  - path: /etc/pam.d/sshd
    owner: root:root
    permissions: "0644"
    content: |
      # Defaults with comments removed and motd disabled
      @include common-auth
      account    required     pam_nologin.so
      @include common-account
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
      session    required     pam_loginuid.so
      session    optional     pam_keyinit.so force revoke
      @include common-session
      session    optional     pam_mail.so standard noenv # [1]
      session    required     pam_limits.so
      session    required     pam_env.so # [1]
      session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
      session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open
      @include common-password
  - path: /etc/ssh/sshd_config
    permissions: "0640"
    content: |
      Include /etc/ssh/sshd_config.d/*.conf
  - path: /etc/ssh/sshd_config.d/base.conf
    permissions: "0640"
    content: |
      ClientAliveInterval 30
      ClientAliveCountMax 240
      UsePAM yes
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      PrintMotd no
      # trial enabling this
      TCPKeepAlive yes
  - path: /etc/ssh/sshd_config.d/rsa.conf
    permissions: "0640"
    content: |
      PubkeyAcceptedAlgorithms +ssh-rsa
      HostKeyAlgorithms +ssh-rsa
  - path: /etc/docker/daemon.json
    owner: root:root
    permissions: "0644"
    content: |
      {"registry-mirrors":["https://mirror.gcr.io"]}
  - path: /etc/containerd/certs.d/docker.io/hosts.toml
    owner: root:root
    permissions: "0644"
    content: |
      server = "https://registry-1.docker.io"
      [host."https://mirror.gcr.io"]
        capabilities = ["pull"]
