---
- hosts: localhost
  become: yes
  become_method: sudo

- name: Kubeadm installation
  apt: state=present name={{ packages }}
  when: ansible_os_family == "Debian"
  vars:
    packages:
    - kubeadm
    - docker.io

- name: Kubeadm installation
  yum: state=present name={{ packages }}
  when: ansible_os_family == "RedHat"
  vars:
    packages:
    - kubeadm
    - docker.io

