on:
  workflow_call:
    inputs:
      scenario-id:
        type: string
        required: true
      subdir:
        type: string
        default: _app
      dockerfile:
        type: string
        default: Dockerfile
      tags:
        type: string
        default: type=raw,value=latest,priority=1000

jobs:
  build-scenario-ctr-image:
    uses: controlplaneio/kubesim-container-images/.github/workflows/templates.yaml@main
    with:
      ctx: simulation-scripts/scenario/${{ inputs.scenario-id }}/${{ inputs.subdir }}
      dockerfile: ${{ inputs.dockerfile }}
      tags: ${{ inputs.tags }}
      name: scenario-${{ inputs.scenario-id }}
    secrets: inherit
