name: 'Terraform Format'
on:
  - pull_request
jobs:
  deploy-aws:
    name: 'Deployments AWS'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/deployments/AWS'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  module-ami:
    name: 'Module AMI'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/modules/AWS/Ami'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  module-bastion:
    name: 'Module Bastion'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/modules/AWS/Bastion'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  module-internalhost:
    name: 'Module InternalHost'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/modules/AWS/InternalHost'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  module-kubernetes:
    name: 'Module Kubernetes'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/modules/AWS/Kubernetes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  module-networking:
    name: 'Module Networking'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/modules/AWS/Networking'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  module-s3storage:
    name: 'Module S3Storage'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/modules/AWS/S3Storage'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  module-securitygroups:
    name: 'Module SecurityGroups'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/modules/AWS/SecurityGroups'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  module-sshkey:
    name: 'Module SshKey'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'terraform/modules/AWS/SshKey'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
