name: Terraform Format

on:
  pull_request:
    paths:
      - terraform/**

jobs:
  deploy-aws:
    name: Deployments AWS
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/deployments/AWS
  module-ami:
    name: Module AMI
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/Ami
  module-bastion:
    name: Module Bastion'
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/Bastion
  module-iam:
    name: Module Iam
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/Iam
  module-internalhost:
    name: Module InternalHost
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/InternalHost
  module-kubernetes:
    name: Module Kubernetes
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/Kubernetes
  module-networking:
    name: Module Networking
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/Networking
  module-s3storage:
    name: Module S3Storage
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/S3Storage
  module-securitygroups:
    name: Module SecurityGroups
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/SecurityGroups
  module-sshkey:
    name: Module SshKey
    runs-on: ubuntu-latest
    uses: ./.github/workflows/terraform-templates.yaml
    with:
      dir: terraform/modules/AWS/SshKey
